test branch
Hillel-DevOps/wordpress_auto_deploy pull request #4
Opened 2020-10-22 18:09 UTC by yupirex

2020-10-22 18:12 UTC, nitrotol requested changes

2020-10-22 18:12 UTC, nitrotol commented on README.MD
> +yupi
Please add your login separate by comma not line break

2020-10-22 18:50 UTC, yupirex commented
q

2020-10-23 13:39 UTC, nitrotol approved these changes

2020-10-24 11:11 UTC, merged